/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HallRouteImport } from './routes/hall'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HallStatusRouteImport } from './routes/hall.status'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HallStatusRoute = HallStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => HallRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hall': typeof HallRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hall/status': typeof HallStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hall': typeof HallRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hall/status': typeof HallStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hall': typeof HallRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hall/status': typeof HallStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hall' | '/sitemap.xml' | '/hall/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hall' | '/sitemap.xml' | '/hall/status'
  id: '__root__' | '/' | '/hall' | '/sitemap.xml' | '/hall/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HallRoute: typeof HallRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall/status': {
      id: '/hall/status'
      path: '/status'
      fullPath: '/hall/status'
      preLoaderRoute: typeof HallStatusRouteImport
      parentRoute: typeof HallRoute
    }
  }
}

interface HallRouteChildren {
  HallStatusRoute: typeof HallStatusRoute
}

const HallRouteChildren: HallRouteChildren = {
  HallStatusRoute: HallStatusRoute,
}

const HallRouteWithChildren = HallRoute._addFileChildren(HallRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HallRoute: HallRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
